version: "2.4"

services:
  pytorch-dist:
    # build
    image: pytorch-dist
    build:
      context: .

    # run
    container_name: pytorch-dist
    environment:
      NNODES: 2
      # NODE_RANK: 0 # set in command line
      NPROC_PER_NODE: 1
      MASTER_ADDR: "172.31.33.116"
      MASTER_PORT: 8080
    runtime: nvidia
    ports:
      - 8080:8080
    network_mode: host
